language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install --upgrade pip
- pip install .[test]
script:
- nosetests
deploy:
  provider: pypi
  user: lodder
  password:
    secure: b/xQG9+iudKyfZoqCZg5RfGz4/bG+7Uhb5UEoJqSaJXa+eKz+f2Jf5ovufn+OeQOy+HKxorsDmbyU8vMP3PCMQB0X8p8yXvMgC51+vg+XIHMjSc//Z1xl4WYZZRdhjpbqBeVG/iEzeMXJzunErUjrlNoW16OHdmYOxiMer/D8yTJpNJNfVdY6I3iZ9gYec0qB9+4cmMsUKZ0WeM9v4eHwR/J+dB2gm13XpTT+AO5YMFFOCuRbHEtrmMAuLTitr94ATQ6v86pXf+H8sxpIsSIP0BPCdfAycB7oC2M1fFdpzohixpQLomALBI1vjdkRVyjvMm+KFELjjHPPltSBNHhcTXYX6Pv1bTGsCqR+pwG2avGg6PqzB1fCjq+2f1LEPIs1cxvFIoMUwKJy3UBouc2tnm0KiQfAtRw4acdN3q/GzGMQAhd5fS8QmlJuMho2Go1EWHORh0kTt6Q/TalmpxeGAy+vzD9r+tyNgYAdfDMOtBAgrFk6yXzT9X5NEL/sc5VlxjmiBuqkDBS96eztICBZy06V24IV7Q/VlPpSy7FjMbTx+cQhWlS3o7oWv+U0sfIfYTxEo+suHvFvTtge3Xv7rX5zrQW6l6cx4qxHUajjV4ZpHr1/YGIXpLBZz3uAX3AFIHIT9J2mguT8/drYTnOgsy6NafhRoGZHiGsB3h01aU=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
notifications:
  email: true
